# -*- coding: utf-8 -*-
"""Kmeans_Semillas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15W6EslzThva0tTueTvUU2UMmRZ7sMvhc

# Agrupamiento - K-Medias

Dataset:
El conjunto de datos “Seeds” describe 210 muestras de granos de trigo, cada una medida con 7 características.

Cada fila corresponde a un grano de trigo y se midieron variables de su geometría a partir de imágenes escaneadas.

🔑 Columnas del dataset



*   Área (A) → Área de la semilla.
*   Perímetro (P) → Longitud del contorno de la semilla.
*   Compacidad (C = 4πA / P²) → Qué tan “compacta” es la semilla (similar a circularidad).
*   Longitud del núcleo (L) → Largo del grano.
*   Ancho del núcleo (W) → Ancho del grano.
*   Coeficiente de asimetría (Asymmetry Coefficient) → Medida de la simetría de la semilla.
*   Longitud del surco del núcleo (Groove Length) → Longitud del surco del grano.
*   Clase (label) → Tipo de trigo (3 variedades distintas).

Para comenzar, ejecute la celda a continuación para cargar nuestros datos.

> **Cita**: El conjunto de datos de semillas utilizado en este ejercicio fue publicado originalmente por el Instituto de Agrofísica de la Academia Polaca de Ciencias en Lublin por Dua, D. y Graff, C. (2019) y puede descargarse del [Repositorio de Aprendizaje Automático de la UCI](http://archive.ics.uci.edu/ml), Universidad de California en Irvine, Facultad de Ciencias de la Información y la Computación.

##Carga de dataset "Semillas"
"""

import pandas as pd

# 📥 Cargar el dataset Seeds desde un archivo CSV en internet
!wget https://raw.githubusercontent.com/MicrosoftDocs/mslearn-introduction-to-machine-learning/main/Data/ml-basics/seeds.csv
data = pd.read_csv('seeds.csv')

# 🔎 Seleccionar las primeras 6 columnas como características (sin incluir la clase)
# Estas columnas son las medidas de cada semilla (área, perímetro, compacidad, etc.)
features = data[data.columns[0:6]]

# 🎲 Mostrar una muestra aleatoria de 10 semillas con sus características
features.sample(10)

"""##Normalización y Transformación"""

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import pandas as pd

# ⚙️ Escalado de características numéricas
# Convertimos todas las variables a un mismo rango [0, 1]
# para evitar que una domine a las demás por su escala.
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(features.iloc[:, 0:6])

# 🧠 Aplicar PCA (Análisis de Componentes Principales)
# Reducimos las 6 dimensiones originales a solo 2
# con el fin de visualizar la estructura de los datos.
pca = PCA(n_components=2, random_state=42)
pca_data = pca.fit_transform(scaled_data)

# 🪄 Convertimos los resultados en un DataFrame para interpretarlos fácilmente
pca_df = pd.DataFrame(pca_data, columns=["PC1", "PC2"])

# 🔍 Mostrar las primeras 10 observaciones transformadas
pca_df.head(10)

"""## Agrupamiento de K-Medias

En este caso utilizaremos el algoritmo K-Medias (K-Means) para generar agrupamientos o clústeres de prueba. Este método de machine learning no supervisado divide un conjunto de datos en K grupos con una varianza similar. El valor de K se define de antemano según el problema.

Proceso general del algoritmo

Inicialización: se eligen al azar K puntos que servirán como los centroides iniciales.

Asignación: cada observación se asocia con el centroide más cercano (según la distancia euclidiana).

Actualización: se recalcula la posición de cada centroide como la media de los puntos que pertenecen a su grupo.

Iteración: los pasos 2 y 3 se repiten hasta que el cambio en la posición de los centroides sea mínimo o se alcance un número máximo de iteraciones.

Convergencia: cuando los centroides dejan de moverse significativamente, el modelo se considera estable.
"""

from sklearn.cluster import KMeans

# 🧩 Crear el modelo de K-Means con 3 grupos
# n_clusters=3 → porque sabemos que hay tres tipos distintos de trigo
# init='k-means++' → inicializa los centroides de forma más eficiente
# n_init=50 → repite el algoritmo varias veces con diferentes puntos iniciales
# max_iter=800 → máximo de iteraciones por ejecución
kmeans_model = KMeans(
    n_clusters=3,
    init='k-means++',
    n_init=50,
    max_iter=800,
    random_state=42
)

# ⚙️ Entrenar el modelo con los datos y obtener las etiquetas de clúster
# Cada semilla será asignada a uno de los grupos (0, 1 o 2)
cluster_labels = kmeans_model.fit_predict(features.values)

# 👀 Mostrar las primeras asignaciones de clúster
# Cada número indica el grupo al que pertenece cada observación
print("Etiquetas de clúster (primeros 15):", cluster_labels[:15])

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# 📊 VISUALIZACIÓN DE LOS CLÚSTERES CON K-MEANS
# ============================================================

import matplotlib.pyplot as plt

# Para Jupyter Notebook, esta línea asegura que los gráficos
# se muestren justo debajo de la celda ejecutada.
# %matplotlib inline

# ------------------------------------------------------------
# 🧩 Función para graficar los clústeres resultantes
# ------------------------------------------------------------
def mostrar_clusters(puntos, etiquetas):
    """
    Dibuja los clústeres generados por K-Means en un plano 2D.
    """
    # Paleta de colores y símbolos para diferenciar los grupos
    color_map = {0: "royalblue", 1: "seagreen", 2: "darkorange"}
    marker_map = {0: "o", 1: "x", 2: "s"}

    # 🔹 Graficar cada punto según su etiqueta
    for i in range(len(etiquetas)):
        plt.scatter(
            puntos[i][0], puntos[i][1],
            c=color_map[etiquetas[i]],
            marker=marker_map[etiquetas[i]],
            s=90, edgecolors="k", linewidths=0.5
        )

    # Personalización del gráfico
    plt.title("Distribución de clústeres (K-Means)")
    plt.xlabel("Componente principal 1")
    plt.ylabel("Componente principal 2")
    plt.grid(alpha=0.2)
    plt.show()

# ------------------------------------------------------------
# 🚀 Llamada a la función de visualización
# ------------------------------------------------------------
# - features_2d: coordenadas en 2D obtenidas con PCA
# - cluster_labels: grupos identificados por el modelo K-Means
mostrar_clusters(features_2d, cluster_labels)

"""Los datos deben separarse en tres grupos distintos. De lo contrario, repita los dos pasos anteriores.

¿Cuál es la utilidad práctica de la agrupación en clústeres? En algunos casos, tendrá datos que necesita agrupar en grupos distintos sin saber cuántos hay ni qué indican. Por ejemplo, una organización de marketing podría querer separar a los clientes en segmentos distintos y luego investigar cómo esos segmentos muestran diferentes comportamientos de compra.

A veces, la agrupación en clústeres se utiliza como primer paso para crear un modelo de clasificación. Se empieza por identificar grupos distintos de puntos de datos y luego se asignan etiquetas de clase a esos grupos. Después, se pueden usar estos datos etiquetados para entrenar un modelo de clasificación.

En el caso de los datos de semillas, las diferentes especies de semillas ya se conocen y están codificadas como 0 (*Kama*), 1 (*Rosa*) o 2 (*Canadian*), por lo que podemos usar estos identificadores para comparar las clasificaciones de especies con los grupos identificados por nuestro algoritmo no supervisado.
"""

# ------------------------------------------------------------
# 🌾 Obtener la columna que indica la especie real de cada semilla
# ------------------------------------------------------------
real_species = data.iloc[:, 7]
# - data.iloc[:, 7] → selecciona la octava columna ("class") del dataset.
# - Esta variable representa la especie real de trigo (tres variedades).
# - La almacenamos en la variable real_species.

# ------------------------------------------------------------
# 🎨 Visualizar las semillas agrupadas por su clase real
# ------------------------------------------------------------
mostrar_clusters(features_2d, real_species.values)
# - features_2d → coordenadas 2D de cada semilla obtenidas con PCA.
# - real_species.values → etiquetas originales (1, 2 o 3).
#   👉 Esto permite comparar cómo se distribuyen las especies verdaderas.
#   👉 El gráfico mostrará los grupos reales en lugar de los predichos por K-Means.

"""##Resultados"""

import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 🧩 Función para comparar visualmente clústeres y clases reales
# ------------------------------------------------------------
def comparar_clusters(muestras, etiquetas_km, etiquetas_reales):
    """
    Muestra dos gráficos lado a lado:
    - A la izquierda: los grupos generados por K-Means.
    - A la derecha: las clases reales del dataset.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))  # una fila, dos columnas

    # 🎨 Paleta de colores y símbolos
    color_map = {0: 'royalblue', 1: 'seagreen', 2: 'darkorange'}
    marker_map = {0: 'o', 1: 'x', 2: 's'}

    # ----------- Panel 1: Resultado del modelo K-Means -----------
    for i in range(len(etiquetas_km)):
        axes[0].scatter(
            muestras[i, 0], muestras[i, 1],
            c=color_map[etiquetas_km[i] % 3],
            marker=marker_map[etiquetas_km[i] % 3],
            s=90, edgecolors="k", linewidths=0.5
        )
    axes[0].set_title("Agrupamiento con K-Means")
    axes[0].set_xlabel("Componente principal 1")
    axes[0].set_ylabel("Componente principal 2")

    # ----------- Panel 2: Clases originales del dataset -----------
    for i in range(len(etiquetas_reales)):
        color = color_map[(etiquetas_reales[i] - 1) % 3]  # -1 porque las clases son 1, 2 y 3
        marker = marker_map[(etiquetas_reales[i] - 1) % 3]
        axes[1].scatter(
            muestras[i, 0], muestras[i, 1],
            c=color, marker=marker,
            s=90, edgecolors="k", linewidths=0.5
        )
    axes[1].set_title("Distribución real de especies")
    axes[1].set_xlabel("Componente principal 1")
    axes[1].set_ylabel("Componente principal 2")

    # 🖼 Ajustar el espacio entre gráficos
    plt.tight_layout()
    plt.show()

# 🚀 Ejecutar la comparación
# - features_2d: datos proyectados en 2D mediante PCA
# - cluster_labels: grupos asignados por K-Means
# - real_species.values: etiquetas reales (1, 2 o 3)
comparar_clusters(features_2d, cluster_labels, real_species.values)

"""# Puede haber algunas diferencias entre las asignaciones de grupos y las etiquetas de clase, pero el modelo K-Means debería haber hecho un trabajo razonable de agrupamiento de las observaciones de modo que las semillas de la misma especie estén generalmente en el mismo grupo."""